export const GET_PATIENTS_ERROR = 'GET_PATIENTS_ERROR';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_ERROR = 'SAVE_ORDER_ERROR';
export const CLEAN_ORDER_DETAIL_MESSAGE = 'CLEAN_ORDER_DETAIL_MESSAGE';
export const CLOSE_ALERT_DIALOG_PAGE = 'CLOSE_ALERT_DIALOG_PAGE';